# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a12d0a065c237a7f503a114cc0ad5afcd16e2b1b346603f46a53ab13e056aa2d44bef6e01bdf3ab9e9d31ce2f0ffb6737cd3d88577cbe91393724018a5502b16

test:
  secret_key_base: 02223f7ab59e6e0e3349aa7b09cb4599ecc0d2119fedabc5460fff06a4585702f1d332ef631171f3512413ecec61103bf03f3f45a424b77f08f5f2766c54b57e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
